// Code generated by embed-grammar-go.js from ini-grammar.jsonic. DO NOT EDIT.

package ini

const grammarText = `
# INI Grammar Definition
# Parsed by a standard Jsonic instance and passed to jsonic.grammar()
# Function references (@ prefixed) are resolved against the refs map in ini.ts

{
  options: {
    rule: { start: ini, exclude: jsonic },
    lex: { emptyResult: {} },
    fixed: {
      token: { '#EQ': '=', '#DOT': '.', '#OB': null, '#CB': null, '#CL': null },
    },
    line: { check: '@line-check' },
    number: { lex: false },
    string: { lex: true, chars: QUOTE_CHARS, abandon: true },
    text: { lex: false },
    comment: {
      def: {
        hash: { eatline: true },
        slash: null,
        multi: null,
        semi: { line: true, start: ';', lex: true, eatline: true },
      },
    },
  },

  rule: {
    ini: {
      open: [
        { s: '#OS', p: table, b: 1 },
        { s: ['#HK #ST #VL', '#EQ'], p: table, b: 2 },
        { s: ['#HV', '#OS'], p: table, b: 2 },
        { s: '#ZZ' },
      ],
    },

    table: {
      open: [
        { s: '#OS', p: dive },
        { s: ['#HK #ST #VL', '#EQ'], p: map, b: 2 },
        { s: ['#HV', '#OS'], p: map, b: 2 },
        { s: '#CS', p: map },
        { s: '#ZZ' },
      ],
      close: [
        { s: '#OS', r: table, b: 1 },
        { s: '#CS', r: table, a: '@table-close-dive' },
        { s: '#ZZ' },
      ],
    },

    dive: {
      open: [
        { s: ['#DK', '#DOT'], a: '@dive-push', p: dive },
        { s: '#DK', a: '@dive-push' },
      ],
      close: [
        { s: '#CS', b: 1 },
      ],
    },

    map: {
      open: {
        alts: [
          { s: ['#HK #ST #VL', '#EQ'], c: '@is-table-parent', p: pair, b: 2 },
          { s: ['#HK #ST #VL'], c: '@is-table-parent', p: pair, b: 1 },
        ],
        inject: { append: true },
      },
      close: [
        { s: '#OS', b: 1 },
        { s: '#ZZ' },
      ],
    },

    pair: {
      open: [
        { s: ['#HK #ST #VL', '#EQ'], c: '@is-table-grandparent', p: val, a: '@pair-key-eq' },
        { s: '#HK', c: '@is-table-grandparent', a: '@pair-key-bool' },
      ],
      close: [
        { s: ['#HK #ST #VL', '#CL'], c: '@is-table-grandparent', e: '@pair-close-err' },
        { s: ['#HK #ST #VL'], b: 1, r: pair },
        { s: '#OS', b: 1 },
      ],
    },
  },
}
`
